### ISSUE TITLE
Where are the labels for link prediction?

### ISSUE THREAD

**Issue by xiehuanyi** [PeterGriffinJin/Patton#2]
Hi, Thanks for your great work!

But I have a question about the link prediction task. I only find `q_text`, `q_n_text`, `k_text`, `k_n_text` in `data/link-prediction/data/Economics/link_prediction/train.text.32.jsonl`. How do I know if there is a link between `q` and `k`?

Looking forward to your reply!

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you for your message!

In link prediction files, the graph is processed in a format that can be fed into the language model. To be specific, ```q``` and ```k``` nodes are linked by an edge. ```q_text``` and ```k_text``` are text information associated with ```q``` and ```k```. ```q_n_text``` and ```k_n_text``` are neighbor text information associated with ```q``` and ```k```. 

Best,
Bowen

**Comment by xiehuanyi** [comment]
Thanks for your response. But what I dont understand is where is negative samples. If `q` and `k` nodes are linked. Don't we have nodes unlinked in test set?

**Comment by xiehuanyi** [comment]
Or, if I want to do the task with some other models like GCN, what should I do to keep the same experiemntal settings?

**Comment by PeterGriffinJin** [comment]
Hi there,

Yes, we use in-batch negatives in both training and testing for computational efficiency. We fix the data ordering for testing so that all the compared models have the same testing data. This can be easily adopted for other models like GCN.
